spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://localhost:3307/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul

    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/schema_dev.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: localhost
      port: 6379

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}
  expiration_time: 720