spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/schema_prod.sql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}
  expiration_time: 1440