# Python 코드 실행 엔진 설정

name: webide

# 코드 실행 엔진 서비스 템플릿
x-code-executor-template: &code-executor-template
  build:
    context: ./sandbox
    dockerfile: Dockerfile
  labels:
    com.docker.compose.service: code-executor
  security_opt:
    - no-new-privileges=true
  restart: unless-stopped
  tty: true
  networks:
    - dev-network

services:
  # Python 코드 실행 엔진 (단일 인스턴스)
  code-executor:
    <<: *code-executor-template
    container_name: webide-code-executor
